### ISSUE TITLE
How to change the parameter in the "enviroment extraction"

### ISSUE THREAD

**Issue by lastshogun** [fhamborg/Giveme5W1H#27]
As mentioned in the question, I would like to modify the "when" and "where" scoring weight according to your paper, but the weight setting format in initialization doesn't look the same as you mentioned in the paper. Please give me some clue how to change W0 W1 W2 W3 in S(when) calculation and W0, W1 in S(where) calculation, thanks a lot.

**Comment by fhamborg** [comment]
We've been reworking Giveme5W1H quite a bit since the paper was published. If you plan to use the exact version from the JCDL paper, you could checkout the version from back then (see https://github.com/fhamborg/Giveme5W1H/commits/master) - there you will find these parameters. However, I'd like to suggest to use the latest version as it is improved (also in regards to the performance) compared to the version from beginning of this year. Feel free to reopen this issue, in case this does not help you :-)
